### ISSUE TITLE
hi，你好，我这边配置完成之后，混淆出来的不是字符

### ISSUE THREAD

**Issue by leiiiooo** [qbeenslee/gradle-proguard-hehe-dictionary#1]
是汉字。 - -|||

**Comment by Qrilee** [comment]
windows下不可以，得去linux或者mac下

**Comment by Trumeet** [comment]
我也是 Windows，用那個 https://github.com/heruoxin/proguard-elder-dictionary 也是很混亂的漢字，是 Windows 的過嗎..

**Comment by Qrilee** [comment]
是的，混淆需要去linux下或者mac下

**Comment by xorzdev** [comment]
汉字+1
